Add missing "session" fixtures in tests/unit/test_req_file.py
Caught by mypy:

    tests/unit/test_req_file.py:342: error: Argument "session" to "parse_reqfile"
    has incompatible type "Callable[[], PipSession]"; expected "PipSession"
    [arg-type]
        ...  reqs = list(parse_reqfile("./parent/req_file.txt", session=session))
                                                                        ^