close a file to prevent a WindowsError
WindowsError: [Error 32] The process cannot access the file because it
is being used by another process: 'C:\\docume~1\\...'

https://mail.python.org/pipermail/distutils-sig/2013-August/022528.html