fix AttributeError: 'thread._local' object has no attribute 'indentation' when i run main command from python under Django, logging fails with this error because threadig state has no attribute indentation, this solution uses helper for optional indentation