Remove unnecessary make_no_network_finder() from tests
Unnecessary since bab1e4f8a1a3ba5f5f08207c83a4e0a7a87ea615 where the
_get_pages method was removed.

This was discovered while experimenting with running mypy on the test
code. Removing it avoids a type failure:

    tests/unit/test_finder.py:36: error: "LinkCollector" has no attribute "_get_pages"
    [attr-defined]
            link_collector._get_pages = lambda locations: []
            ^