Catch misleading ImportError
If pip cache data get out of sync with the Python version used to create
them, it can cause a misleading pickling error.

When serialize.py tries to deserialize pickled cache data, packages
with an out-of-date path will generate an ImportError that may refer to
any number of imports, some of which can be paths that look
like external packages, such as urllib3 or requests. Example:

```
File "/Users/higgins/Projects/cfgov-refresh/.tox/unittest-fast/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py",line 168, in _loads_v1
cached = pickle.loads(data)
ImportError: No module named urllib3._collections
```

It can be hard to understand and get out of this state, because attempting
to load a cached package in any local virtual environment will hit an
import error that doesn't seem related. Also, tox tests that generate
a new environment will also bomb if they try to install a cached package.

Adding ImportError as an exception allows a user to get out of this
state by skipping the cache, the way a ValueError does, and allows
the cache to get back in sync for users who have upgraded Python.

It appears [this commenter](https://github.com/pypa/pip/issues/5079#issuecomment-374239659) on #5079 encountered the same pickling error.

Users who realize it's a cache problem can use `--no-cache-dir` on all
their installs, or clear the system pip cache, but a self-healing solution
would help toilers like me.