PermissionError when installing pip
Building Python 3.6 on my system from source, ensurepip attempts to deploy pip. Pip fails, giving the following error:

Exception:
Traceback (most recent call last):
  File "/tmp/tmpvjrijrr_/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/tmpvjrijrr_/pip-9.0.1-py2.py3-none-any.whl/pip/commands/install.py", line 272, in run
    with self._build_session(options) as session:
  File "/tmp/tmpvjrijrr_/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/tmp/tmpvjrijrr_/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/tmp/tmpvjrijrr_/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/tmp/tmpvjrijrr_/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/tmp/tmpvjrijrr_/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/distro.py", line 595, in __init__
    self._distro_release_info = self._get_distro_release_info()
  File "/tmp/tmpvjrijrr_/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/distro.py", line 995, in _get_distro_release_info
    distro_info = self._parse_distro_release_file(filepath)
  File "/tmp/tmpvjrijrr_/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/distro.py", line 1015, in _parse_distro_release_file
    with open(filepath) as fp:
PermissionError: [Errno 13] Permission denied: '/etc/BMW-release'


This is because I do not have read permissions on that file. The try...except block simply skips reading the file on that error, as if it isn't a file.