Make sphinx.ext.extlinks captions actual string templates
In Sphinx 3, this used to be a prefix, but it is the full caption since Sphinx 4:

https://github.com/sphinx-doc/sphinx/commit/fb39974486ab09320f0cf45f3c0ba0175f04d7d6

With Sphinx 6, captions without %s fail:

https://github.com/sphinx-doc/sphinx/commit/ce31e1c0c7b32f6be93186e0fef076ef65ff0b05

    Exception occurred:
    File "/usr/lib/python3.11/site-packages/sphinx/ext/extlinks.py", line 103, in role
    title = caption % part
            ~~~~~~~~^~~~~~
    TypeError: not all arguments converted during string formatting

Fixes Fedora downstream report: https://bugzilla.redhat.com/2180479