Check support of sysconfig.get_preferred_scheme() in a different way
Support for the feature sysconfig.get_preferred_scheme
(added on Python 3.10 - see bpo-43312) was checked based
on the Python version (see commit
ca4aa121a9f7d876b4513cadf8d9e54c8515416a
"Use Python 3.10 sysconfig.get_preferred_scheme()").

Unfortunately, this API seems to be introduced with the
3.10.beta Cpython builds and does not seem to be part of
the 3.10.alpha versions.

Hence, on these versions, pip fails with exception:
    AttributeError: module 'sysconfig' has no attribute 'get_preferred_scheme'

The solution chosen is to check if the function exists
in the sysconfig module using introspection instead of
relying on Python versions.