Because git does not disallow '#' in branch names, handle them
Considering the following URL 'git+ssh://git@github.com/owner/reponame.git@issue#2035#egg=Reponame', previously we'd get an error similar to:
```
Collecting Reponame from git+ssh://git@github.com/owner/reponame.git@issue#2035#egg=Reponame
  Cloning ssh://git@github.com/owner/reponame.git (to issue) to /tmp/vampas/pip-build-ftjipp8c/Reponame
  Could not find a tag or branch 'issue', assuming commit.
error: pathspec 'issue' did not match any file(s) known to git.
```

With this change, we check for an existing '#' in the frag part of the
parsed URL and add back the remaining of the path in such case.

We now get something like:
```
Collecting Reponame from git+ssh://git@github.com/owner/reponame.git@issue#2035#egg=Reponame
  Cloning ssh://git@github.com/owner/reponame.git (to revision issue#2035) to /tmp/vampas/pip-install-jjs7njl1/Reponame
Installing collected packages: Reponame
  Running setup.py install for Reponame ... done
Successfully installed Reponame-5.2
```