Work around failing test due to distutils.version issue
In py3k the following fails, handle this and use string comparison in worst
case.

Tested on 2.6 and 3.2

>> from distutils.version import LooseVersion as LV
>>> v1, v2, v3 = (LV('1.1'), LV('1.1.2'), LV('1.1a1'))
>>> v1 > v2
False
>>> v1 > v3
False
>>> v2 > v3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "distutils/version.py", line 70, in __gt__
    c = self._cmp(other)
  File "distutils/version.py", line 343, in _cmp
    if self.version < other.version:
TypeError: unorderable types: int() < str()